import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const projectRoot = resolve(import.meta.dirname, '..')
const scanPageSource = readFileSync(resolve(projectRoot, 'src/components/ScanPage.tsx'), 'utf8')
const settingsPageSource = readFileSync(resolve(projectRoot, 'src/components/SettingsPage.tsx'), 'utf8')
const overviewPageSource = readFileSync(resolve(projectRoot, 'src/components/OverviewPage.tsx'), 'utf8')
const configApiSource = readFileSync(resolve(projectRoot, 'src/api/config.ts'), 'utf8')
const configStoreSource = readFileSync(resolve(projectRoot, 'src/stores/configStore.ts'), 'utf8')
const scannerStoreSource = readFileSync(resolve(projectRoot, 'src/stores/scannerStore.ts'), 'utf8')
const quarantineApiSource = readFileSync(resolve(projectRoot, 'src/api/quarantine.ts'), 'utf8')
const configModelSource = readFileSync(resolve(projectRoot, 'src-tauri/src/models/config.rs'), 'utf8')
const allowlistCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/allowlist.rs'), 'utf8')
const exclusionsCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/exclusions.rs'), 'utf8')
const runtimeListStoreSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/runtime_list_store.rs'), 'utf8')
const pathPolicyServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/path_policy_service.rs'), 'utf8')
const scannerCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/scanner.rs'), 'utf8')
const snapshotCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/snapshot.rs'), 'utf8')
const processScannerServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/process_scanner_service.rs'), 'utf8')
const fileMonitorServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/file_monitor_service.rs'), 'utf8')
const processMonitorServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/process_monitor_service.rs'), 'utf8')
const snapshotServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/snapshot_service.rs'), 'utf8')
const appSource = readFileSync(resolve(projectRoot, 'src/App.tsx'), 'utf8')
const interceptionModalSource = readFileSync(resolve(projectRoot, 'src/components/InterceptionModal.tsx'), 'utf8')
const scanResultCacheServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/scan_result_cache_service.rs'), 'utf8')
const readmeSource = readFileSync(resolve(projectRoot, 'README.md'), 'utf8')
const zhI18nSource = readFileSync(resolve(projectRoot, 'config/i18n/zh-CN.json'), 'utf8')
const enI18nSource = readFileSync(resolve(projectRoot, 'config/i18n/en-US.json'), 'utf8')
const gitignoreSource = readFileSync(resolve(projectRoot, '.gitignore'), 'utf8')
const tauriIgnoreSource = readFileSync(resolve(projectRoot, '.taurignore'), 'utf8')
const srcTauriIgnoreSource = readFileSync(resolve(projectRoot, 'src-tauri/.taurignore'), 'utf8')
const viteConfigSource = readFileSync(resolve(projectRoot, 'vite.config.ts'), 'utf8')
const tauriMainSource = readFileSync(resolve(projectRoot, 'src-tauri/src/main.rs'), 'utf8')
const globalCssSource = readFileSync(resolve(projectRoot, 'src/styles/global.css'), 'utf8')
const quarantinePageSource = readFileSync(resolve(projectRoot, 'src/components/QuarantinePage.tsx'), 'utf8')
const mainTsxSource = readFileSync(resolve(projectRoot, 'src/main.tsx'), 'utf8')
const interceptionWindowAppSource = readFileSync(resolve(projectRoot, 'src/components/InterceptionWindowApp.tsx'), 'utf8')
const interceptionWindowServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/interception_window_service.rs'), 'utf8')
const interceptionServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/interception_service.rs'), 'utf8')
const defaultCapabilitySource = readFileSync(resolve(projectRoot, 'src-tauri/capabilities/default.json'), 'utf8')
const interceptionCapabilitySource = readFileSync(resolve(projectRoot, 'src-tauri/capabilities/interception.json'), 'utf8')
const interceptionPayloadSource = readFileSync(resolve(projectRoot, 'src/utils/interceptionPayload.ts'), 'utf8')

test('ScanPage only renders clear and trust actions inside the threat-result branch', () => {
  const threatBranchIndex = scanPageSource.indexOf(') : threats.length > 0 ? (')
  const clearThreatIndex = scanPageSource.indexOf('清除威胁', threatBranchIndex)
  const addTrustIndex = scanPageSource.indexOf('添加信任', threatBranchIndex)

  assert.notEqual(threatBranchIndex, -1)
  assert.ok(clearThreatIndex > threatBranchIndex)
  assert.ok(addTrustIndex > threatBranchIndex)
  assert.match(scanPageSource, /disabled=\{!hasSelectedThreats \|\| threatAction !== null\}/)
})

test('ScanPage wires threat actions to quarantine and allowlist APIs', () => {
  assert.match(scanPageSource, /import \{ addToAllowlist \} from '\.\.\/api\/allowlist'/)
  assert.match(scanPageSource, /import \{ isolateFile \} from '\.\.\/api\/quarantine'/)
  assert.match(scanPageSource, /await isolateFile\(threatPath, threat\.threatType \|\| threat\.verdict\)/)
  assert.match(scanPageSource, /await addToAllowlist\(threatPath, 'Added from scan threat result'\)/)
  assert.match(scanPageSource, /removeScanResultsByPath\(clearedThreatPaths\)/)
  assert.match(scannerStoreSource, /removeScanResultsByPath: \(paths: string\[\]\) => void/)
  assert.match(scannerStoreSource, /scanResults: remainingResults/)
})

test('Settings page merges exclusions and allowed items into one trust workflow', () => {
  assert.match(settingsPageSource, /<div className="settings-group-title">信任项目<\/div>/)
  assert.match(settingsPageSource, /handleAddTrustItem/)
  assert.match(settingsPageSource, /handleRemoveTrustItem/)
  assert.match(settingsPageSource, /confirmDeleteTrustIndex !== null/)
  assert.match(settingsPageSource, /trustItems\.map/)
  assert.doesNotMatch(settingsPageSource, /settings-tabs/)
  assert.doesNotMatch(settingsPageSource, /<h3>允许项目<\/h3>/)
  assert.doesNotMatch(settingsPageSource, /<h3>扫描排除项<\/h3>/)
  assert.doesNotMatch(settingsPageSource, /id: 'exclusions' as const/)
  assert.doesNotMatch(settingsPageSource, /id: 'allowlist' as const/)
  assert.doesNotMatch(settingsPageSource, /id: 'training' as const/)
  assert.doesNotMatch(settingsPageSource, /ML 模型训练/)
  assert.doesNotMatch(settingsPageSource, /activeTab === 'exclusions'/)
  assert.doesNotMatch(settingsPageSource, /activeTab === 'allowlist'/)
  assert.doesNotMatch(settingsPageSource, /activeTab === 'training'/)
})

test('Model training feature is removed from UI docs and language packs', () => {
  assert.doesNotMatch(readmeSource, /ML 机器学习训练/)
  assert.doesNotMatch(readmeSource, /training\.ts/)
  assert.doesNotMatch(readmeSource, /training_service/)
  assert.doesNotMatch(zhI18nSource, /settings_dev_train/)
  assert.doesNotMatch(enI18nSource, /settings_dev_train/)
  assert.doesNotMatch(zhI18nSource, /训练中/)
  assert.doesNotMatch(enI18nSource, /Training/)
})

test('Overview page controls the real scan engine start and stop commands', () => {
  assert.match(overviewPageSource, /import \{ scannerHealth, startEngine, stopEngine \} from '\.\.\/api\/scanner'/)
  assert.match(overviewPageSource, /useState<'running' \| 'stopped' \| 'error' \| 'loading'>\('loading'\)/)
  assert.match(overviewPageSource, /health\.status === 'running'/)
  assert.match(overviewPageSource, /health\.status === 'stopped'/)
  assert.match(overviewPageSource, /await stopEngine\(\)/)
  assert.match(overviewPageSource, /await startEngine\(\)/)
  assert.match(overviewPageSource, /引擎已停止/)
  assert.match(overviewPageSource, /停止引擎/)
  assert.match(overviewPageSource, /启动引擎/)
})

test('Config store exposes one trust workflow backed by allowlist and exclusions', () => {
  assert.match(configStoreSource, /export interface TrustItemEntry/)
  assert.match(configStoreSource, /export const mergeTrustItems/)
  assert.match(configStoreSource, /trustItems: TrustItemEntry\[\]/)
  assert.match(configStoreSource, /loadTrustItems: \(\) => Promise<void>/)
  assert.match(configStoreSource, /addTrustItem: \(path: string, entryType: 'file' \| 'directory' \| 'process', description\?: string\) => Promise<void>/)
  assert.match(configStoreSource, /removeTrustItem: \(path: string\) => Promise<void>/)
  assert.match(configStoreSource, /const \[exclusions, allowlist\] = await Promise\.all\(\[listExclusions\(\), listAllowlist\(\)\]\)/)
  assert.match(configStoreSource, /if \(entryType === 'file' && !matchedAllowlist\)/)
  assert.match(configStoreSource, /await addExclusion\(path, entryType, description\)/)
  assert.match(configStoreSource, /await addToAllowlist\(path, description\)/)
  assert.match(configStoreSource, /await removeExclusion\(matchedExclusion\.path\)/)
  assert.match(configStoreSource, /await removeFromAllowlist\(matchedAllowlist\.path\)/)
})

test('Quarantine API normalizes backend snake_case fields before UI usage', () => {
  assert.match(quarantineApiSource, /interface RawQuarantineItem/)
  assert.match(quarantineApiSource, /originalPath: item\.originalPath \?\? item\.original_path \?\? ''/)
  assert.match(quarantineApiSource, /fileSize: item\.fileSize \?\? item\.file_size \?\? 0/)
  assert.match(quarantineApiSource, /return items\.map\(normalizeQuarantineItem\)/)
})

test('Config save creates the target config directory before writing', () => {
  assert.match(configModelSource, /fn resolve_save_path\(\) -> PathBuf/)
  assert.match(configModelSource, /fs::create_dir_all\(parent\)\?/)
  assert.match(configModelSource, /fs::write\(config_path, content\)\?/)
})

test('README documents Fluent 2 threat action button rules', () => {
  assert.match(readmeSource, /Fluent 2 设计系统/)
  assert.match(readmeSource, /"清除威胁"和"添加信任"按钮仅在扫描结果中存在威胁时渲染/)
  assert.match(readmeSource, /未选择威胁时保持 disabled 状态/)
})

test('README separates tracked config files from runtime generated config files', () => {
  assert.match(readmeSource, /配置文件职责/)
  assert.match(readmeSource, /可提交的静态配置/)
  assert.match(readmeSource, /运行时生成文件/)
  assert.match(readmeSource, /config\/app\.json/)
  assert.match(readmeSource, /config\/scan_rules\.json/)
  assert.match(readmeSource, /config\/etw_match_rules\.json/)
  assert.match(readmeSource, /config\/i18n\/zh-CN\.json/)
  assert.match(readmeSource, /config\/i18n\/en-US\.json/)
  assert.match(readmeSource, /config\/scan_cache\.json/)
  assert.match(readmeSource, /config\/quarantine_index\.json/)
  assert.match(readmeSource, /config\/startup_allowlist\.enc/)
  assert.match(readmeSource, /%APPDATA%\/AnXinSecurity\/runtime\/startup_allowlist\.json/)
  assert.match(readmeSource, /%APPDATA%\/AnXinSecurity\/runtime\/exclusions\.json/)
  assert.match(readmeSource, /npm run dev/)
  assert.match(gitignoreSource, /data\/runtime\//)
})

test('Allowlist and exclusions commands persist mutable lists outside config app json', () => {
  assert.match(pathPolicyServiceSource, /ALLOWLIST_RUNTIME_FILE: &str = "startup_allowlist\.json"/)
  assert.match(pathPolicyServiceSource, /load_runtime_list\(ALLOWLIST_RUNTIME_FILE, ALLOWLIST_LEGACY_FIELD\)/)
  assert.match(allowlistCommandSource, /load_allowlist_entries\(\)/)
  assert.match(allowlistCommandSource, /save_runtime_list\(ALLOWLIST_RUNTIME_FILE, entries\)/)
  assert.doesNotMatch(allowlistCommandSource, /use crate::models::config::AppConfig/)
  assert.doesNotMatch(allowlistCommandSource, /State<'_, Arc<Mutex<AppConfig>>>/)
  assert.doesNotMatch(allowlistCommandSource, /config\.save/)

  assert.match(pathPolicyServiceSource, /EXCLUSIONS_RUNTIME_FILE: &str = "exclusions\.json"/)
  assert.match(pathPolicyServiceSource, /load_runtime_list\(EXCLUSIONS_RUNTIME_FILE, EXCLUSIONS_LEGACY_FIELD\)/)
  assert.match(exclusionsCommandSource, /load_exclusion_entries\(\)/)
  assert.match(exclusionsCommandSource, /save_runtime_list\(EXCLUSIONS_RUNTIME_FILE, entries\)/)
  assert.doesNotMatch(exclusionsCommandSource, /use crate::models::config::AppConfig/)
  assert.doesNotMatch(exclusionsCommandSource, /State<'_, Arc<Mutex<AppConfig>>>/)
  assert.doesNotMatch(exclusionsCommandSource, /config\.save/)
})

test('Runtime list store migrates legacy app config fields without writing repository config', () => {
  assert.match(runtimeListStoreSource, /PathBuf::from\(app_data\)[\s\S]*?\.join\("AnXinSecurity"\)[\s\S]*?\.join\("runtime"\)/)
  assert.match(runtimeListStoreSource, /PathBuf::from\("data"\)\.join\("runtime"\)/)
  assert.match(runtimeListStoreSource, /load_legacy_list_from_app_config\(legacy_field\)/)
  assert.match(runtimeListStoreSource, /save_runtime_list\(file_name, &legacy_items\)\?/)
  assert.match(configModelSource, /existing_object\.remove\("exclusions"\)/)
  assert.match(configModelSource, /existing_object\.remove\("startupAllowlist"\)/)
})

test('Runtime list store encrypts allowlist and exclusions with DPAPI', () => {
  assert.match(runtimeListStoreSource, /CryptProtectData/)
  assert.match(runtimeListStoreSource, /CryptUnprotectData/)
  assert.match(runtimeListStoreSource, /ENCRYPTED_RUNTIME_LIST_MAGIC/)
  assert.match(runtimeListStoreSource, /protect_runtime_bytes\(content\.as_bytes\(\)\)\?/)
  assert.match(runtimeListStoreSource, /unprotect_runtime_bytes\(&content\)\?/)
  assert.match(runtimeListStoreSource, /Rejected unencrypted runtime list/)
  assert.match(runtimeListStoreSource, /dpapi_runtime_bytes_round_trip_and_detect_tampering/)
  assert.match(readmeSource, /Windows DPAPI 加密并带完整性校验/)
})

test('Scan and monitor paths honor runtime exclusions and allowlist', () => {
  assert.match(pathPolicyServiceSource, /pub fn should_skip_security_scan\(path: &str\) -> Result<bool, String>/)
  assert.match(pathPolicyServiceSource, /is_excluded_path\(path\)\?/)
  assert.match(pathPolicyServiceSource, /is_allowed_path\(path\)/)
  assert.match(pathPolicyServiceSource, /pub fn load_allowlist_entries\(\) -> Result<Vec<AllowlistEntry>, String>/)
  assert.match(pathPolicyServiceSource, /pub fn load_exclusion_entries\(\) -> Result<Vec<ExclusionEntry>, String>/)
  assert.match(scannerCommandSource, /should_skip_security_scan\(&file_path\)\?/)
  assert.match(scannerCommandSource, /skipped_scan_result\(&file_path\)/)
  assert.match(scannerCommandSource, /should_skip_security_scan\(file_path\)\?/)
  assert.match(processScannerServiceSource, /should_skip_security_scan\(target_path\)/)
  assert.match(fileMonitorServiceSource, /should_skip_security_scan\(&file_path\)/)
  assert.match(processMonitorServiceSource, /should_skip_security_scan\(&image_path\)/)
  assert.match(snapshotServiceSource, /load_path_policy_snapshot\(\)\?/)
  assert.match(snapshotServiceSource, /path_policy\.should_skip_security_scan\(&proc_info\.path\)/)
})

test('Process and startup scans use cached engine results for process modules', () => {
  assert.match(processScannerServiceSource, /enumerate_process_modules\(pid\)/)
  assert.match(processScannerServiceSource, /scan_or_get_cached\(engine, target_path\)/)
  assert.match(processScannerServiceSource, /"targetType": target_type/)
  assert.match(processScannerServiceSource, /"source": "process_scanner"/)
  assert.match(processScannerServiceSource, /should_skip_security_scan\(target_path\)/)
  assert.match(processScannerServiceSource, /detect_process_image_integrity\(pid, &path/)
  assert.match(processScannerServiceSource, /process_hollowing/)
  assert.match(processScannerServiceSource, /VirtualQueryEx/)
  assert.match(processScannerServiceSource, /ReadProcessMemory/)
  assert.match(processScannerServiceSource, /MEM_IMAGE/)
  assert.match(processScannerServiceSource, /AddressOfEntryPoint|entry_point_rva/)
  assert.match(processScannerServiceSource, /SizeOfImage|size_of_image/)

  assert.match(snapshotServiceSource, /enumerate_process_module_info_with_timeout\(\s*proc_info\.pid/)
  assert.match(snapshotServiceSource, /prepare_startup_module_targets\(modules\)/)
  assert.match(snapshotServiceSource, /detect_process_image_integrity_from_modules\(/)
  assert.doesNotMatch(snapshotServiceSource, /detect_process_image_integrity\(\s*proc_info\.pid/)
  assert.match(snapshotServiceSource, /scan_or_get_cached_deferred_with_hash\(\s*engine,\s*target_path,\s*precomputed_sha256_hex\.filter\(\|_\| target_version_key\.is_some\(\)\)/)
  assert.match(snapshotServiceSource, /cache\.flush_pending\(\)/)
  assert.match(snapshotServiceSource, /policy_already_checked: bool/)
  assert.match(snapshotServiceSource, /if !policy_already_checked && path_policy\.should_skip_security_scan_cached\(target_path, None\)/)
  assert.match(snapshotServiceSource, /target_version_key: Option<&str>/)
  assert.match(snapshotServiceSource, /HashMap<String, StartupScanCachedOutcome>/)
  assert.match(snapshotServiceSource, /target_version_key\.map\(startup_scan_cache_key\)/)
  assert.match(snapshotServiceSource, /startup_scan_results[\s\S]*\.get\(key\)/)
  assert.match(snapshotServiceSource, /StartupScanCachedOutcome::Failed\(error\.clone\(\)\)/)
  assert.match(snapshotServiceSource, /StartupScanCachedOutcome::Completed\(result\.clone\(\)\)/)
  assert.doesNotMatch(snapshotServiceSource, /startup_scan_results\.insert\(target_scan_key\.to_string\(\)/)
  assert.match(snapshotServiceSource, /path_policy\.should_skip_by_path_only\(&proc_info\.path\)/)
  assert.match(pathPolicyServiceSource, /struct PreparedPathLookup/)
  assert.match(pathPolicyServiceSource, /lookup_cache: std::sync::Arc<Mutex<HashMap<String, PreparedPathLookup>>>/)
  assert.match(pathPolicyServiceSource, /fn lookup_for_path\(&self, path: &str\) -> PreparedPathLookup/)
  assert.match(pathPolicyServiceSource, /let lookup = self\.lookup_for_path\(path\)/)
  assert.match(pathPolicyServiceSource, /fn prepare_path_lookup\(path: &str\) -> PreparedPathLookup/)
  assert.match(pathPolicyServiceSource, /self\.is_excluded_lookup\(&lookup\) \|\| self\.is_allowed_path_by_exact_lookup\(&lookup\)/)
  assert.match(pathPolicyServiceSource, /struct PreparedAllowlistIndex \{[\s\S]*exact_paths: HashSet<String>[\s\S]*hashes: HashSet<String>/)
  assert.match(pathPolicyServiceSource, /allowlist: PreparedAllowlistIndex/)
  assert.match(pathPolicyServiceSource, /self\.allowlist\.exact_paths\.contains\(&lookup\.normalized_path\)/)
  assert.match(pathPolicyServiceSource, /self\.allowlist\.hashes\.contains\(current_hash\)/)
  assert.match(pathPolicyServiceSource, /normalized_sha256_hex/)
  assert.doesNotMatch(pathPolicyServiceSource, /entry\s*\.entry\s*\.hash/)
  assert.doesNotMatch(pathPolicyServiceSource, /for entry in &self\.allowlist/)
  assert.doesNotMatch(pathPolicyServiceSource, /matches_prepared_exclusion[\s\S]*entry\.entry\.path\.to_ascii_lowercase\(\)/)
  assert.match(snapshotServiceSource, /let process_scan_key = proc_info\.scan_key\.clone\(\)/)
  assert.match(snapshotServiceSource, /scan_key: startup_scan_key\(&path\)/)
  assert.match(snapshotServiceSource, /struct StartupTargetSnapshot \{[\s\S]*scan_key: String/)
  assert.match(snapshotServiceSource, /struct ProcInfo \{[\s\S]*scan_key: String/)
  assert.match(snapshotServiceSource, /unique_module_paths\.insert\(module\.scan_key\.clone\(\)\)/)
  assert.match(snapshotServiceSource, /startup_module_is_process_image\(&module\.scan_key, &process_scan_key\)/)
  assert.match(snapshotServiceSource, /path_policy\.should_skip_by_path_only\(&module_path\)/)
  assert.match(snapshotServiceSource, /inspect_startup_target_with_scan_key\(&module_path, module\.scan_key\.clone\(\)\)/)
  assert.match(snapshotServiceSource, /fn inspect_startup_target_with_scan_key\(path: &str, scan_key: String\) -> StartupTargetSnapshot/)
  assert.match(snapshotServiceSource, /let process_is_trusted = process_signature_verdict[\s\S]*?is_some_and\(\|verdict\| verdict\.trusted\)/)
  assert.match(snapshotServiceSource, /let process_hash_decision = if process_path_scannable && !process_is_trusted \{[\s\S]*?path_policy\.hash_after_path_miss_cached\(\s*&proc_info\.path,\s*process_target\.signature_cache_key\.as_deref\(\),\s*\)[\s\S]*?HashAfterPathMissDecision::default\(\)/)
  assert.match(snapshotServiceSource, /process_hash_decision\.sha256_hex\.as_deref\(\)/)
  assert.match(snapshotServiceSource, /module_signature_cache_key = module_result\.signature_cache_key/)
  assert.match(snapshotServiceSource, /let module_hash_decision = path_policy\.hash_after_path_miss_cached\(\s*&module_path,\s*module_signature_cache_key\.as_deref\(\)/)
  assert.match(snapshotServiceSource, /module_hash_decision\.sha256_hex\.as_deref\(\)/)
  assert.match(pathPolicyServiceSource, /pub fn should_skip_by_hash_after_path_miss_cached/)
  assert.match(pathPolicyServiceSource, /pub fn hash_after_path_miss_cached/)
  assert.match(pathPolicyServiceSource, /pub struct HashAfterPathMissDecision/)
  assert.match(pathPolicyServiceSource, /file_version_cache_key\(path\)\.filter\(\|key\| key == cache_key\)/)
  assert.match(pathPolicyServiceSource, /let scoped_cache_key = format!\("hash-after-path-miss\|\{\}", current_cache_key\)/)
  assert.doesNotMatch(pathPolicyServiceSource, /should_skip_by_hash_after_path_miss_cached[\s\S]*self\.is_allowed_path_by_exact_lookup/)
  assert.match(snapshotServiceSource, /inspect_startup_target_with_scan_key\(&proc_info\.path, process_scan_key\.clone\(\)\)/)
  assert.match(snapshotServiceSource, /\"process\",\s*&proc_info\.path,\s*&process_target\.scan_key,/)
  assert.match(snapshotServiceSource, /process_target\.signature_cache_key\.as_deref\(\)/)
  assert.match(snapshotServiceSource, /let module_scan_key = module_result\.scan_key/)
  assert.match(snapshotServiceSource, /\"module\",\s*&module_path,\s*&module_scan_key,/)
  assert.match(snapshotServiceSource, /module_signature_cache_key\.as_deref\(\)/)
  assert.match(snapshotServiceSource, /startup_signature_cache\s*\.verify_file_for_target_async\(\s*trust\.clone\(\),\s*&proc_info\.path,\s*&process_target/)
  assert.match(snapshotServiceSource, /startup_signature_cache\s*\.verify_module_targets_concurrent\(/)
  assert.match(snapshotServiceSource, /startup_module_signature_verify_timeout\(signature_verify_timeout, target_scan_timeout\)/)
  assert.match(snapshotServiceSource, /STARTUP_MODULE_SIGNATURE_TIMEOUT_MULTIPLIER/)
  assert.match(snapshotServiceSource, /all_modules_requiring_signature/)
  assert.match(snapshotServiceSource, /verify_file_with_timeout_async\(trust, path_for_verify, timeout\)\.await/)
  assert.match(snapshotServiceSource, /tokio::time::timeout\(\s*timeout,\s*tokio::task::spawn_blocking/)
  assert.match(snapshotServiceSource, /self\.entries[\s\S]*\.insert\(completed\.cache_key\.clone\(\), completed\.verdict\.clone\(\)\)/)
  assert.match(snapshotServiceSource, /StartupModuleSignatureResult \{[\s\S]*pid: u32/)
  assert.match(snapshotServiceSource, /process_name: String/)
  assert.match(snapshotServiceSource, /inspect_startup_target\(path\)/)
  assert.match(snapshotServiceSource, /path_scan_key: process_scan_key\.clone\(\)/)
  assert.match(snapshotServiceSource, /startup_scan_key\(path\) == target\.path_scan_key\.as_str\(\)/)
  assert.match(snapshotServiceSource, /fn startup_signature_cache_key\(path: &str\) -> Option<String>/)
  assert.match(snapshotServiceSource, /超时、任务失败或验证错误仍返回不可信\/Unknown/)
  assert.doesNotMatch(snapshotServiceSource, /if process_path_scannable \{\s*match enumerate_process_modules/)
  assert.match(processScannerServiceSource, /detect_process_image_integrity\(pid, &path/)
  assert.match(snapshotServiceSource, /image_integrity_alerts/)
  assert.match(snapshotServiceSource, /unknown_processes/)
  assert.match(snapshotServiceSource, /unknown_modules/)
  assert.match(snapshotServiceSource, /module_enumeration_access_denied/)
  assert.match(snapshotServiceSource, /First access-denied module enumeration failure/)
  assert.doesNotMatch(snapshotServiceSource, /threat_type: Some\("unsigned_process"\.to_string\(\)\)/)
  assert.doesNotMatch(snapshotServiceSource, /threat_type: Some\("unsigned_module"\.to_string\(\)\)/)
  assert.match(snapshotServiceSource, /Unsigned module kept as alert-only/)
  assert.match(snapshotServiceSource, /unsigned_module_alerts/)
  assert.match(snapshotServiceSource, /skipped_trusted_modules/)
  assert.match(snapshotServiceSource, /process_target\.is_scannable\(\)/)
  assert.match(snapshotServiceSource, /module_target\.skip_reason\.is_some\(\)/)
  assert.match(snapshotServiceSource, /tokio::time::timeout/)
  assert.match(snapshotServiceSource, /verify_module_targets_concurrent/)
  assert.match(snapshotServiceSource, /resolve_startup_signature_verify_concurrency\(options\.signature_verify_concurrency\)/)
  assert.match(snapshotServiceSource, /std::thread::available_parallelism\(\)/)
  assert.match(snapshotServiceSource, /module_enumeration_timeout =[\s\S]*options\.module_enumeration_timeout_ms\.max\(1\)/)
  assert.match(snapshotServiceSource, /enumerate_process_module_info_with_timeout/)
  assert.match(snapshotServiceSource, /spawn_blocking\(move \|\|/)
  assert.match(snapshotServiceSource, /ordered_results\.sort_by_key/)
  assert.match(snapshotServiceSource, /Slow scan warning/)
  assert.match(snapshotServiceSource, /SnapshotScanOptions/)
  assert.match(tauriMainSource, /startup_snapshot_slow_warn_ms/)
  assert.match(tauriMainSource, /module_enumeration_access_denied/)
  assert.match(tauriMainSource, /target_scan_timeout_ms: config\.scanner\.timeout_ms/)
  assert.match(tauriMainSource, /startup_signature_verify_timeout_ms/)
  assert.match(tauriMainSource, /startup_signature_verify_concurrency/)
  assert.match(tauriMainSource, /startup_module_enumeration_timeout_ms/)
  assert.match(configModelSource, /startup_snapshot_slow_warn_ms: u64/)
  assert.match(configModelSource, /startup_module_enumeration_timeout_ms: u64/)
  assert.match(configModelSource, /startup_signature_verify_timeout_ms: u64/)
  assert.match(configModelSource, /startup_signature_verify_concurrency: usize/)
  assert.match(configApiSource, /startupModuleEnumerationTimeoutMs: number/)
  assert.match(configApiSource, /startupSignatureVerifyConcurrency: number/)
  assert.match(configStoreSource, /startupModuleEnumerationTimeoutMs: 1000/)
  assert.match(configStoreSource, /startupSignatureVerifyConcurrency: 0/)
  assert.match(snapshotServiceSource, /"source": "startup_snapshot"/)
  assert.match(snapshotServiceSource, /"targetType": target_type/)
  assert.match(snapshotServiceSource, /spawn_startup_revocation_checks/)
  assert.match(snapshotServiceSource, /verify_file_with_revocation/)
  assert.match(snapshotServiceSource, /tokio::task::JoinSet::new\(\)/)
  assert.match(snapshotServiceSource, /tokio::sync::Semaphore::new\(max_concurrency\)/)
  assert.match(snapshotServiceSource, /query_process_image_path\(target\.pid\)/)
  assert.match(snapshotServiceSource, /file_write_time_epoch_ms/)
  assert.match(snapshotServiceSource, /RevocationCheckOutcome::ImageChanged/)
  assert.match(snapshotServiceSource, /revocation_target_changed/)
  assert.match(snapshotServiceSource, /timeout,\s*async move/)
  assert.match(snapshotServiceSource, /revocation_alerts/)
  assert.match(snapshotServiceSource, /revocation_unknown_critical/)
  assert.match(snapshotServiceSource, /app_handle\.emit\("snapshot-result", &result\)/)
  assert.doesNotMatch(snapshotServiceSource, /certificate-revoked/)
  assert.doesNotMatch(snapshotServiceSource, /certificate-revocation-unknown/)
  assert.match(snapshotServiceSource, /scanned_modules/)
  assert.match(snapshotServiceSource, /malicious_modules/)
  assert.match(snapshotServiceSource, /cache_hits/)
  assert.match(snapshotServiceSource, /SnapshotPerformanceStats/)
  assert.match(snapshotServiceSource, /process_enumeration_ms/)
  assert.match(snapshotServiceSource, /module_enumeration_ms/)
  assert.match(snapshotServiceSource, /signature_verification_ms/)
  assert.match(snapshotServiceSource, /process_signature_verification_ms/)
  assert.match(snapshotServiceSource, /module_signature_verification_ms/)
  assert.match(snapshotServiceSource, /signature_verify_concurrency/)
  assert.match(snapshotServiceSource, /target_scan_ms/)
  assert.match(snapshotServiceSource, /process_target_scan_ms/)
  assert.match(snapshotServiceSource, /module_target_scan_ms/)
  assert.match(snapshotServiceSource, /signature_cache_hits/)
  assert.match(snapshotServiceSource, /signature_coalesced_waiters/)
  assert.match(snapshotServiceSource, /Module signature batch start/)
  assert.match(snapshotServiceSource, /Module signature batch done/)
  assert.match(snapshotServiceSource, /Module scan batch start/)
  assert.match(snapshotServiceSource, /Module scan batch progress/)
  assert.match(snapshotServiceSource, /Module scan batch done/)
  assert.match(snapshotServiceSource, /Target scan detail/)
  assert.match(snapshotServiceSource, /should_log_startup_target_scan_detail/)
  assert.match(snapshotServiceSource, /startup_target_scan_source\(snapshot_cache_hit, scan_result\.cache_hit\)/)
  assert.match(snapshotServiceSource, /short_hash_prefix\(&scan_result\.hash_hex\)/)
  assert.match(snapshotServiceSource, /process_signature_timeouts/)
  assert.match(snapshotServiceSource, /module_signature_timeouts/)
  assert.match(snapshotServiceSource, /module_enumeration_timeouts/)
  assert.match(snapshotServiceSource, /target_scan_cache_hits/)
  assert.match(snapshotServiceSource, /StartupSnapshot\] Performance/)
  assert.match(snapshotCommandSource, /empty_snapshot_result\(\)/)
  assert.match(snapshotCommandSource, /SnapshotPerformanceStats::default\(\)/)
  assert.match(snapshotServiceSource, /StartupScanOutcome::Malicious \{ cache_hit \} => \{[\s\S]*?module_scan_was_malicious = true;[\s\S]*?malicious_modules \+= 1/)
  assert.match(snapshotServiceSource, /if module_signature_untrusted && !module_scan_was_malicious \{[\s\S]*?Unsigned module observed without malware verdict/)
  assert.doesNotMatch(snapshotServiceSource, /enqueue_startup_signature_interception\([\s\S]*?"module",[\s\S]*?&module_path/)
  assert.match(processScannerServiceSource, /pub\(crate\) fn query_process_image_path/)
  assert.match(tauriMainSource, /startup_revocation_check_timeout_ms/)
  assert.match(tauriMainSource, /startup_revocation_check_concurrency/)
  assert.match(configModelSource, /startup_revocation_check_timeout_ms: u64/)
  assert.match(configModelSource, /startup_revocation_check_concurrency: usize/)

  assert.match(scanResultCacheServiceSource, /SCAN_RESULT_CACHE_FILE: &str = "scan_results\.json"/)
  assert.match(scanResultCacheServiceSource, /load_runtime_list::<PersistedScanCacheEntry>/)
  assert.match(scanResultCacheServiceSource, /save_runtime_list\(SCAN_RESULT_CACHE_FILE, &entries\)/)
  assert.match(scanResultCacheServiceSource, /scan_or_get_cached_deferred/)
  assert.match(scanResultCacheServiceSource, /scan_or_get_cached_deferred_with_hash/)
  assert.match(scanResultCacheServiceSource, /precomputed_sha256_hex/)
  assert.match(scanResultCacheServiceSource, /normalized_sha256_hex/)
  assert.match(scanResultCacheServiceSource, /hashSource/)
  assert.match(scanResultCacheServiceSource, /flush_pending/)
  assert.match(scanResultCacheServiceSource, /sha256_hex_of_file\(file_path\)/)
  assert.match(scanResultCacheServiceSource, /ANXIN_SCAN_CACHE_DEBUG/)
  assert.match(scanResultCacheServiceSource, /Lookup detail: outcome=hit/)
  assert.match(scanResultCacheServiceSource, /Lookup detail: outcome=miss/)
  assert.match(scanResultCacheServiceSource, /hashMs/)
  assert.match(scanResultCacheServiceSource, /engineMs/)
  assert.match(scanResultCacheServiceSource, /raw_result/)
})

test('Interception UI maps structured startup reasons through i18n keys', () => {
  assert.match(interceptionWindowAppSource, /normalizeInterceptionEventPayload/)
  assert.match(interceptionPayloadSource, /parseInterceptionPayload/)
  assert.match(interceptionPayloadSource, /interceptionReasonI18nKey/)
  assert.match(interceptionPayloadSource, /masquerade_path_mismatch: 'intercept_reason_masquerade_path_mismatch'/)
  assert.match(interceptionPayloadSource, /certificate_revoked: 'intercept_reason_certificate_revoked'/)
  assert.match(interceptionPayloadSource, /revocation_target_changed: 'intercept_reason_revocation_target_changed'/)
  assert.match(interceptionPayloadSource, /t\(reasonKey/)
  assert.match(interceptionModalSource, /useI18nStore/)
  assert.match(interceptionModalSource, /t\('intercept_btn_block_process'/)
  assert.match(interceptionModalSource, /t\('intercept_btn_allow_run'/)
  assert.match(zhI18nSource, /"intercept_reason_masquerade_path_mismatch"/)
  assert.match(zhI18nSource, /"intercept_reason_certificate_revoked"/)
  assert.match(zhI18nSource, /"intercept_reason_revocation_target_changed"/)
  assert.match(enI18nSource, /"intercept_reason_masquerade_path_mismatch"/)
  assert.match(enI18nSource, /"intercept_reason_certificate_revoked"/)
  assert.match(enI18nSource, /"intercept_reason_revocation_target_changed"/)
})

test('Interception modal overlay enables pointer events while visible', () => {
  assert.match(interceptionModalSource, /modal-overlay visible/)
  assert.match(globalCssSource, /\.modal-overlay\.visible \{[\s\S]*pointer-events: auto;/)
})

test('Interception alerts render in an independent focused window', () => {
  assert.match(mainTsxSource, /getCurrentWindow\(\)/)
  assert.match(mainTsxSource, /currentWindow\.label === 'interception' \? InterceptionWindowApp : App/)
  assert.match(interceptionWindowAppSource, /listen<Record<string, unknown>>\('process-intercepted'/)
  assert.match(interceptionWindowAppSource, /cleanupEventListener/)
  assert.match(interceptionWindowAppSource, /Event listener registration failed/)
  assert.match(interceptionWindowAppSource, /peekCurrentInterception\(\)/)
  assert.match(interceptionWindowAppSource, /getCurrentWindow\(\)/)
  assert.match(interceptionWindowAppSource, /setAlwaysOnTop\(true\)/)
  assert.match(interceptionWindowAppSource, /requestUserAttention\(UserAttentionType\.Critical\)/)
  assert.match(interceptionWindowAppSource, /has-interception/)
  assert.match(interceptionWindowAppSource, /DEFAULT_INTERCEPTION_ACTION = 'block'/)
  assert.match(interceptionWindowAppSource, /INTERCEPTION_AUTO_DECISION_SECONDS = 60/)
  assert.match(interceptionWindowAppSource, /autoDecisionTriggeredPidRef/)
  assert.match(interceptionWindowAppSource, /submitDecision\(DEFAULT_INTERCEPTION_ACTION\)/)
  assert.match(interceptionWindowAppSource, /submitDecision\('allow'\)/)
  assert.match(interceptionWindowAppSource, /submitDecision\('block'\)/)
  assert.match(interceptionWindowAppSource, /handleInterception\(pid, action\)[\s\S]*?current\?\.pid === pid \? null : current/)
  assert.doesNotMatch(appSource, /listen<Record<string, unknown>>\('process-intercepted'/)
  assert.doesNotMatch(appSource, /<InterceptionModal/)
  assert.match(interceptionWindowServiceSource, /INTERCEPTION_WINDOW_LABEL: &str = "interception"/)
  assert.match(interceptionWindowServiceSource, /WebviewWindowBuilder::new\([\s\S]*WebviewUrl::App\("index\.html"\.into\(\)\)/)
  assert.match(interceptionWindowServiceSource, /\.inner_size\(640\.0,\s*480\.0\)/)
  assert.match(interceptionWindowServiceSource, /\.min_inner_size\(640\.0,\s*480\.0\)/)
  assert.match(interceptionWindowServiceSource, /\.resizable\(false\)/)
  assert.match(interceptionWindowServiceSource, /\.transparent\(false\)/)
  assert.match(interceptionWindowServiceSource, /\.always_on_top\(true\)/)
  assert.match(interceptionWindowServiceSource, /CloseRequested[\s\S]*prevent_close\(\)/)
  assert.match(interceptionServiceSource, /show_interception_window\(app_handle\)/)
  assert.match(interceptionServiceSource, /\.emit_to\("interception", "process-intercepted"/)
  assert.doesNotMatch(interceptionServiceSource, /app_handle\.emit\("process-intercepted"/)
  assert.match(tauriMainSource, /prepare_interception_window\(app\.handle\(\)\)/)
  assert.match(defaultCapabilitySource, /"windows": \["main"\]/)
  assert.match(interceptionCapabilitySource, /"identifier": "interception"/)
  assert.match(interceptionCapabilitySource, /"windows": \["interception"\]/)
  assert.match(interceptionCapabilitySource, /"core:default"/)
  assert.match(interceptionCapabilitySource, /"core:event:allow-listen"/)
  assert.match(interceptionCapabilitySource, /"core:window:allow-show"/)
  assert.match(interceptionCapabilitySource, /"core:window:allow-hide"/)
  assert.match(interceptionCapabilitySource, /"core:window:allow-unminimize"/)
  assert.match(interceptionCapabilitySource, /"core:window:allow-set-always-on-top"/)
  assert.match(interceptionCapabilitySource, /"core:window:allow-request-user-attention"/)
  assert.match(interceptionCapabilitySource, /"core:window:allow-set-focus"/)
  assert.doesNotMatch(interceptionCapabilitySource, /"shell:default"/)
  assert.doesNotMatch(interceptionCapabilitySource, /"fs:default"/)
  assert.match(interceptionModalSource, /mode === 'window'/)
  assert.match(interceptionModalSource, /defaultAction\?: 'allow' \| 'block'/)
  assert.match(interceptionModalSource, /remainingSeconds\?: number/)
  assert.match(interceptionModalSource, /autoDecisionSeconds\?: number/)
  assert.match(interceptionModalSource, /decisionPending\?: boolean/)
  assert.match(interceptionModalSource, /const useStyles = makeStyles/)
  assert.match(interceptionModalSource, /overlayWindow:/)
  assert.match(interceptionModalSource, /surfaceWindow:/)
  assert.match(interceptionModalSource, /headerDraggable:/)
  assert.match(interceptionModalSource, /countdown:/)
  assert.match(interceptionModalSource, /timeoutTrack:/)
  assert.match(interceptionModalSource, /timeoutBar:/)
  assert.match(interceptionModalSource, /className=\{`\$\{styles\.overlay\} \$\{isWindowMode \? styles\.overlayWindow : ''\}`\}/)
  assert.match(interceptionModalSource, /className=\{`\$\{styles\.surface\} \$\{isWindowMode \? styles\.surfaceWindow : ''\}`\}/)
  assert.match(interceptionModalSource, /className=\{`\$\{styles\.header\} \$\{isWindowMode \? styles\.headerDraggable : ''\}`\}/)
  assert.match(interceptionModalSource, /data-tauri-drag-region/)
  assert.match(interceptionModalSource, /appearance="outline"[\s\S]*?onClick=\{onAllow\}[\s\S]*?disabled=\{decisionPending\}/)
  assert.match(interceptionModalSource, /appearance="primary"[\s\S]*?onClick=\{onBlock\}[\s\S]*?disabled=\{decisionPending\}/)
  assert.match(interceptionModalSource, /autoFocus=\{defaultAction === 'block'\}/)
  assert.match(interceptionModalSource, /decisionPending/)
  assert.match(interceptionModalSource, /width: '100%'/)
  assert.match(interceptionModalSource, /minHeight: '100%'/)
  assert.match(interceptionModalSource, /boxShadow: isWindowMode/)
  assert.doesNotMatch(interceptionModalSource, /className="btn/)
  assert.doesNotMatch(interceptionModalSource, /interception-overlay-window/)
  assert.doesNotMatch(interceptionModalSource, /interception-window-surface/)
})

test('Interception commands use the managed Arc service so queue rotation can continue', () => {
  const interceptionCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/interception.rs'), 'utf8')

  assert.match(tauriMainSource, /let interception_service = Arc::new\(InterceptionService::new\(\)\)/)
  assert.match(tauriMainSource, /app\.manage\(interception_service\.clone\(\)\)/)
  assert.doesNotMatch(interceptionCommandSource, /State<'_, InterceptionService>/)
  assert.match(interceptionCommandSource, /handle_interception[\s\S]*interception: tauri::State<'_, Arc<InterceptionService>>/)
  assert.match(interceptionCommandSource, /entry_for_pid\(pid\)/)
  assert.match(interceptionCommandSource, /mark_allowed_temporarily\(&entry\)/)
  assert.match(interceptionCommandSource, /resume_process_by_pid\(pid\)/)
  assert.match(interceptionCommandSource, /remove_temporary_allow\(&entry\)/)
  assert.match(interceptionCommandSource, /complete_allow\(pid\)/)
  assert.match(interceptionCommandSource, /terminate_process_by_pid\(pid\)/)
  assert.match(interceptionCommandSource, /get_interception_queue[\s\S]*interception: tauri::State<'_, Arc<InterceptionService>>/)
  assert.match(interceptionCommandSource, /clear_interception_queue[\s\S]*interception: tauri::State<'_, Arc<InterceptionService>>/)
  assert.match(interceptionCommandSource, /get_interception_status[\s\S]*interception: tauri::State<'_, Arc<InterceptionService>>/)
  assert.match(interceptionCommandSource, /peek_current_interception[\s\S]*interception: tauri::State<'_, Arc<InterceptionService>>/)
  assert.match(interceptionCommandSource, /interception\.mark_decision_with_window\(pid, decision, &app_handle\)/)
  assert.match(interceptionCommandSource, /interception\.try_show_next\(&app_handle\)/)
  assert.doesNotMatch(interceptionCommandSource, /terminate_process_internal/)
})

test('Interception alert uses risk-themed warning styling', () => {
  assert.match(interceptionModalSource, /alertStrip:/)
  assert.match(interceptionModalSource, /className=\{styles\.alertStrip\}/)
  assert.match(interceptionModalSource, /intercept_security_alert/)
  assert.match(interceptionModalSource, /t\('intercept_btn_allow_run'/)
  assert.match(interceptionModalSource, /t\('intercept_btn_block_process'/)
  assert.match(interceptionModalSource, /colorPaletteRedBackground2/)
  assert.match(interceptionModalSource, /colorPaletteRedForeground2/)
  assert.match(interceptionModalSource, /colorPaletteRedBorder2/)
  assert.match(interceptionModalSource, /backgroundColor: riskStyle\.text/)
  assert.match(interceptionModalSource, /borderColor: riskStyle\.text/)
  assert.match(globalCssSource, /\.interception-window-root\.has-interception/)
  assert.match(interceptionModalSource, /detailValue:/)
  assert.match(interceptionModalSource, /textOverflow: 'ellipsis'/)
  assert.match(interceptionModalSource, /title=\{filePath\}/)
  assert.match(zhI18nSource, /"intercept_security_alert"/)
  assert.match(enI18nSource, /"intercept_security_alert"/)
})

test('Dev watchers ignore runtime quarantine and database files', () => {
  assert.match(viteConfigSource, /\*\*\/data\/\*\*/)
  assert.match(viteConfigSource, /\*\*\/logs\/\*\*/)
  assert.match(viteConfigSource, /\*\*\/config\/quarantine_index\.json/)
  assert.match(viteConfigSource, /\*\*\/config\/scan_cache\.json/)
  assert.match(tauriIgnoreSource, /data\/\*\*/)
  assert.match(tauriIgnoreSource, /logs\/\*\*/)
  assert.match(tauriIgnoreSource, /config\/quarantine_index\.json/)
  assert.match(tauriIgnoreSource, /src-tauri\/data\/\*\*/)
  assert.match(srcTauriIgnoreSource, /data\/\*\*/)
  assert.match(srcTauriIgnoreSource, /logs\/\*\*/)
  assert.match(srcTauriIgnoreSource, /target\/\*\*/)
  assert.match(gitignoreSource, /src-tauri\/data\//)
})

test('Behavior SQLite database uses app data instead of repository runtime paths', () => {
  assert.match(tauriMainSource, /fn resolve_behavior_database_path\(config: &AppConfig\) -> Result<PathBuf, String>/)
  assert.match(tauriMainSource, /std::env::var\("APPDATA"\)/)
  assert.match(tauriMainSource, /PathBuf::from\(app_data\)[\s\S]*?\.join\("AnXinSecurity"\)[\s\S]*?\.join\(&configured_dir\)/)
  assert.match(tauriMainSource, /fn migrate_legacy_behavior_database/)
  assert.match(tauriMainSource, /std::fs::copy\(&legacy_path, target_path\)/)
  assert.match(tauriMainSource, /let db_root = resolve_behavior_database_path\(&config\)\?/)
  assert.doesNotMatch(tauriMainSource, /let mut db_root = std::env::current_dir/)
})

test('File hook pipe receiver starts during app setup before active watchers', () => {
  assert.match(tauriMainSource, /let hook_service = HookService::new\(\)/)
  assert.match(tauriMainSource, /\.start\("anxin_security_filehook", app\.handle\(\)\.clone\(\)\)/)
  assert.match(tauriMainSource, /Failed to start file hook pipe service/)
  assert.match(tauriMainSource, /hook_pipe_service_started/)
  assert.match(tauriMainSource, /pipeError=2/)
  assert.match(tauriMainSource, /app\.manage\(Arc::new\(hook_service\)\)/)
})

test('New-process scanner starts before the full startup snapshot while APIHook remains after it', () => {
  const processScannerManageIndex = tauriMainSource.indexOf('let process_scanner = ProcessScannerService::new()')
  const scannerStartCallIndex = tauriMainSource.indexOf('start_runtime_process_scanner_before_snapshot(', processScannerManageIndex)
  const snapshotTaskIndex = tauriMainSource.indexOf('let app_handle_snapshot = app.handle().clone()', processScannerManageIndex)
  const takeSnapshotIndex = tauriMainSource.indexOf('.take_startup_snapshot(', snapshotTaskIndex)
  const apiHookStartCallIndex = tauriMainSource.indexOf('start_apihook_process_watcher_after_snapshot(', takeSnapshotIndex)

  assert.notEqual(processScannerManageIndex, -1)
  assert.ok(scannerStartCallIndex > processScannerManageIndex)
  assert.ok(snapshotTaskIndex > scannerStartCallIndex)
  assert.ok(takeSnapshotIndex > snapshotTaskIndex)
  assert.ok(apiHookStartCallIndex > takeSnapshotIndex)
  assert.match(tauriMainSource, /Process scanner started before startup snapshot/)
  assert.match(tauriMainSource, /APIHook process watcher started after startup snapshot/)
  assert.doesNotMatch(tauriMainSource, /Process scanner started after startup snapshot/)
})

test('Quarantine table keeps status and action controls readable', () => {
  assert.match(quarantinePageSource, /className="table-container"/)
  assert.match(quarantinePageSource, /className="table-scroll"/)
  assert.match(quarantinePageSource, /className="quarantine-status-cell"/)
  assert.match(quarantinePageSource, /className="quarantine-actions"/)
  assert.match(globalCssSource, /\.table-container/)
  assert.match(globalCssSource, /min-width: 1120px/)
  assert.match(globalCssSource, /\.quarantine-status-cell \.severity-badge/)
  assert.match(globalCssSource, /white-space: nowrap/)
  assert.match(globalCssSource, /\.quarantine-actions \.btn-sm/)
})

test('Quarantine confirmation dialog uses modal surface background', () => {
  assert.match(quarantinePageSource, /className="modal-overlay"/)
  assert.match(quarantinePageSource, /className="modal-body"/)
  assert.doesNotMatch(quarantinePageSource, /className="modal-content"/)
  assert.match(globalCssSource, /\.modal-surface/)
  assert.match(globalCssSource, /background: var\(--acrylic-dark\)/)
  assert.match(globalCssSource, /html\[data-theme="light"\] \.modal-surface/)
  assert.match(globalCssSource, /\.quarantine-confirm-modal/)
})
