import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const projectRoot = resolve(import.meta.dirname, '..')
const scanPageSource = readFileSync(resolve(projectRoot, 'src/components/ScanPage.tsx'), 'utf8')
const settingsPageSource = readFileSync(resolve(projectRoot, 'src/components/SettingsPage.tsx'), 'utf8')
const overviewPageSource = readFileSync(resolve(projectRoot, 'src/components/OverviewPage.tsx'), 'utf8')
const configStoreSource = readFileSync(resolve(projectRoot, 'src/stores/configStore.ts'), 'utf8')
const scannerStoreSource = readFileSync(resolve(projectRoot, 'src/stores/scannerStore.ts'), 'utf8')
const quarantineApiSource = readFileSync(resolve(projectRoot, 'src/api/quarantine.ts'), 'utf8')
const configModelSource = readFileSync(resolve(projectRoot, 'src-tauri/src/models/config.rs'), 'utf8')
const allowlistCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/allowlist.rs'), 'utf8')
const exclusionsCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/exclusions.rs'), 'utf8')
const runtimeListStoreSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/runtime_list_store.rs'), 'utf8')
const pathPolicyServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/path_policy_service.rs'), 'utf8')
const scannerCommandSource = readFileSync(resolve(projectRoot, 'src-tauri/src/commands/scanner.rs'), 'utf8')
const processScannerServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/process_scanner_service.rs'), 'utf8')
const fileMonitorServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/file_monitor_service.rs'), 'utf8')
const processMonitorServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/process_monitor_service.rs'), 'utf8')
const snapshotServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/snapshot_service.rs'), 'utf8')
const scanResultCacheServiceSource = readFileSync(resolve(projectRoot, 'src-tauri/src/services/scan_result_cache_service.rs'), 'utf8')
const readmeSource = readFileSync(resolve(projectRoot, 'README.md'), 'utf8')
const zhI18nSource = readFileSync(resolve(projectRoot, 'config/i18n/zh-CN.json'), 'utf8')
const enI18nSource = readFileSync(resolve(projectRoot, 'config/i18n/en-US.json'), 'utf8')
const gitignoreSource = readFileSync(resolve(projectRoot, '.gitignore'), 'utf8')
const tauriIgnoreSource = readFileSync(resolve(projectRoot, '.taurignore'), 'utf8')
const srcTauriIgnoreSource = readFileSync(resolve(projectRoot, 'src-tauri/.taurignore'), 'utf8')
const viteConfigSource = readFileSync(resolve(projectRoot, 'vite.config.ts'), 'utf8')
const tauriMainSource = readFileSync(resolve(projectRoot, 'src-tauri/src/main.rs'), 'utf8')
const globalCssSource = readFileSync(resolve(projectRoot, 'src/styles/global.css'), 'utf8')
const quarantinePageSource = readFileSync(resolve(projectRoot, 'src/components/QuarantinePage.tsx'), 'utf8')

test('ScanPage only renders clear and trust actions inside the threat-result branch', () => {
  const threatBranchIndex = scanPageSource.indexOf(') : threats.length > 0 ? (')
  const clearThreatIndex = scanPageSource.indexOf('清除威胁', threatBranchIndex)
  const addTrustIndex = scanPageSource.indexOf('添加信任', threatBranchIndex)

  assert.notEqual(threatBranchIndex, -1)
  assert.ok(clearThreatIndex > threatBranchIndex)
  assert.ok(addTrustIndex > threatBranchIndex)
  assert.match(scanPageSource, /disabled=\{!hasSelectedThreats \|\| threatAction !== null\}/)
})

test('ScanPage wires threat actions to quarantine and allowlist APIs', () => {
  assert.match(scanPageSource, /import \{ addToAllowlist \} from '\.\.\/api\/allowlist'/)
  assert.match(scanPageSource, /import \{ isolateFile \} from '\.\.\/api\/quarantine'/)
  assert.match(scanPageSource, /await isolateFile\(threatPath, threat\.threatType \|\| threat\.verdict\)/)
  assert.match(scanPageSource, /await addToAllowlist\(threatPath, 'Added from scan threat result'\)/)
  assert.match(scanPageSource, /removeScanResultsByPath\(clearedThreatPaths\)/)
  assert.match(scannerStoreSource, /removeScanResultsByPath: \(paths: string\[\]\) => void/)
  assert.match(scannerStoreSource, /scanResults: remainingResults/)
})

test('Settings page merges exclusions and allowed items into one trust workflow', () => {
  assert.match(settingsPageSource, /useState<'general'\|'trust'\|'dev'>\('general'\)/)
  assert.match(settingsPageSource, /id: 'trust' as const, label: `信任项目/)
  assert.match(settingsPageSource, /activeTab === 'trust'/)
  assert.match(settingsPageSource, /<h3>信任项目<\/h3>/)
  assert.match(settingsPageSource, /handleAddTrustItem/)
  assert.match(settingsPageSource, /handleRemoveTrustItem/)
  assert.match(settingsPageSource, /confirmDeleteTrustIndex !== null/)
  assert.match(settingsPageSource, /trustItems\.map/)
  assert.doesNotMatch(settingsPageSource, /<h3>允许项目<\/h3>/)
  assert.doesNotMatch(settingsPageSource, /<h3>扫描排除项<\/h3>/)
  assert.doesNotMatch(settingsPageSource, /id: 'exclusions' as const/)
  assert.doesNotMatch(settingsPageSource, /id: 'allowlist' as const/)
  assert.doesNotMatch(settingsPageSource, /id: 'training' as const/)
  assert.doesNotMatch(settingsPageSource, /ML 模型训练/)
  assert.doesNotMatch(settingsPageSource, /activeTab === 'exclusions'/)
  assert.doesNotMatch(settingsPageSource, /activeTab === 'allowlist'/)
  assert.doesNotMatch(settingsPageSource, /activeTab === 'training'/)
})

test('Model training feature is removed from UI docs and language packs', () => {
  assert.doesNotMatch(readmeSource, /ML 机器学习训练/)
  assert.doesNotMatch(readmeSource, /training\.ts/)
  assert.doesNotMatch(readmeSource, /training_service/)
  assert.doesNotMatch(zhI18nSource, /settings_dev_train/)
  assert.doesNotMatch(enI18nSource, /settings_dev_train/)
  assert.doesNotMatch(zhI18nSource, /训练中/)
  assert.doesNotMatch(enI18nSource, /Training/)
})

test('Overview page controls the real scan engine start and stop commands', () => {
  assert.match(overviewPageSource, /import \{ scannerHealth, startEngine, stopEngine \} from '\.\.\/api\/scanner'/)
  assert.match(overviewPageSource, /useState<'running' \| 'stopped' \| 'error' \| 'loading'>\('loading'\)/)
  assert.match(overviewPageSource, /health\.status === 'running'/)
  assert.match(overviewPageSource, /health\.status === 'stopped'/)
  assert.match(overviewPageSource, /await stopEngine\(\)/)
  assert.match(overviewPageSource, /await startEngine\(\)/)
  assert.match(overviewPageSource, /引擎已停止/)
  assert.match(overviewPageSource, /停止引擎/)
  assert.match(overviewPageSource, /启动引擎/)
})

test('Config store exposes one trust workflow backed by allowlist and exclusions', () => {
  assert.match(configStoreSource, /export interface TrustItemEntry/)
  assert.match(configStoreSource, /export const mergeTrustItems/)
  assert.match(configStoreSource, /trustItems: TrustItemEntry\[\]/)
  assert.match(configStoreSource, /loadTrustItems: \(\) => Promise<void>/)
  assert.match(configStoreSource, /addTrustItem: \(path: string, entryType: 'file' \| 'directory' \| 'process', description\?: string\) => Promise<void>/)
  assert.match(configStoreSource, /removeTrustItem: \(path: string\) => Promise<void>/)
  assert.match(configStoreSource, /const \[exclusions, allowlist\] = await Promise\.all\(\[listExclusions\(\), listAllowlist\(\)\]\)/)
  assert.match(configStoreSource, /if \(entryType === 'file' && !matchedAllowlist\)/)
  assert.match(configStoreSource, /await addExclusion\(path, entryType, description\)/)
  assert.match(configStoreSource, /await addToAllowlist\(path, description\)/)
  assert.match(configStoreSource, /await removeExclusion\(matchedExclusion\.path\)/)
  assert.match(configStoreSource, /await removeFromAllowlist\(matchedAllowlist\.path\)/)
})

test('Quarantine API normalizes backend snake_case fields before UI usage', () => {
  assert.match(quarantineApiSource, /interface RawQuarantineItem/)
  assert.match(quarantineApiSource, /originalPath: item\.originalPath \?\? item\.original_path \?\? ''/)
  assert.match(quarantineApiSource, /fileSize: item\.fileSize \?\? item\.file_size \?\? 0/)
  assert.match(quarantineApiSource, /return items\.map\(normalizeQuarantineItem\)/)
})

test('Config save creates the target config directory before writing', () => {
  assert.match(configModelSource, /fn resolve_save_path\(\) -> PathBuf/)
  assert.match(configModelSource, /fs::create_dir_all\(parent\)\?/)
  assert.match(configModelSource, /fs::write\(config_path, content\)\?/)
})

test('README documents Fluent 2 threat action button rules', () => {
  assert.match(readmeSource, /Fluent 2 设计系统/)
  assert.match(readmeSource, /"清除威胁"和"添加信任"按钮仅在扫描结果中存在威胁时渲染/)
  assert.match(readmeSource, /未选择威胁时保持 disabled 状态/)
})

test('README separates tracked config files from runtime generated config files', () => {
  assert.match(readmeSource, /配置文件职责/)
  assert.match(readmeSource, /可提交的静态配置/)
  assert.match(readmeSource, /运行时生成文件/)
  assert.match(readmeSource, /config\/app\.json/)
  assert.match(readmeSource, /config\/scan_rules\.json/)
  assert.match(readmeSource, /config\/etw_match_rules\.json/)
  assert.match(readmeSource, /config\/i18n\/zh-CN\.json/)
  assert.match(readmeSource, /config\/i18n\/en-US\.json/)
  assert.match(readmeSource, /config\/scan_cache\.json/)
  assert.match(readmeSource, /config\/quarantine_index\.json/)
  assert.match(readmeSource, /config\/startup_allowlist\.enc/)
  assert.match(readmeSource, /%APPDATA%\/AnXinSecurity\/runtime\/startup_allowlist\.json/)
  assert.match(readmeSource, /%APPDATA%\/AnXinSecurity\/runtime\/exclusions\.json/)
  assert.match(readmeSource, /npm run dev/)
  assert.match(gitignoreSource, /data\/runtime\//)
})

test('Allowlist and exclusions commands persist mutable lists outside config app json', () => {
  assert.match(pathPolicyServiceSource, /ALLOWLIST_RUNTIME_FILE: &str = "startup_allowlist\.json"/)
  assert.match(pathPolicyServiceSource, /load_runtime_list\(ALLOWLIST_RUNTIME_FILE, ALLOWLIST_LEGACY_FIELD\)/)
  assert.match(allowlistCommandSource, /load_allowlist_entries\(\)/)
  assert.match(allowlistCommandSource, /save_runtime_list\(ALLOWLIST_RUNTIME_FILE, entries\)/)
  assert.doesNotMatch(allowlistCommandSource, /use crate::models::config::AppConfig/)
  assert.doesNotMatch(allowlistCommandSource, /State<'_, Arc<Mutex<AppConfig>>>/)
  assert.doesNotMatch(allowlistCommandSource, /config\.save/)

  assert.match(pathPolicyServiceSource, /EXCLUSIONS_RUNTIME_FILE: &str = "exclusions\.json"/)
  assert.match(pathPolicyServiceSource, /load_runtime_list\(EXCLUSIONS_RUNTIME_FILE, EXCLUSIONS_LEGACY_FIELD\)/)
  assert.match(exclusionsCommandSource, /load_exclusion_entries\(\)/)
  assert.match(exclusionsCommandSource, /save_runtime_list\(EXCLUSIONS_RUNTIME_FILE, entries\)/)
  assert.doesNotMatch(exclusionsCommandSource, /use crate::models::config::AppConfig/)
  assert.doesNotMatch(exclusionsCommandSource, /State<'_, Arc<Mutex<AppConfig>>>/)
  assert.doesNotMatch(exclusionsCommandSource, /config\.save/)
})

test('Runtime list store migrates legacy app config fields without writing repository config', () => {
  assert.match(runtimeListStoreSource, /PathBuf::from\(app_data\)[\s\S]*?\.join\("AnXinSecurity"\)[\s\S]*?\.join\("runtime"\)/)
  assert.match(runtimeListStoreSource, /PathBuf::from\("data"\)\.join\("runtime"\)/)
  assert.match(runtimeListStoreSource, /load_legacy_list_from_app_config\(legacy_field\)/)
  assert.match(runtimeListStoreSource, /save_runtime_list\(file_name, &legacy_items\)\?/)
  assert.match(configModelSource, /existing_object\.remove\("exclusions"\)/)
  assert.match(configModelSource, /existing_object\.remove\("startupAllowlist"\)/)
})

test('Runtime list store encrypts allowlist and exclusions with DPAPI', () => {
  assert.match(runtimeListStoreSource, /CryptProtectData/)
  assert.match(runtimeListStoreSource, /CryptUnprotectData/)
  assert.match(runtimeListStoreSource, /ENCRYPTED_RUNTIME_LIST_MAGIC/)
  assert.match(runtimeListStoreSource, /protect_runtime_bytes\(content\.as_bytes\(\)\)\?/)
  assert.match(runtimeListStoreSource, /unprotect_runtime_bytes\(&content\)\?/)
  assert.match(runtimeListStoreSource, /Rejected unencrypted runtime list/)
  assert.match(runtimeListStoreSource, /dpapi_runtime_bytes_round_trip_and_detect_tampering/)
  assert.match(readmeSource, /Windows DPAPI 加密并带完整性校验/)
})

test('Scan and monitor paths honor runtime exclusions and allowlist', () => {
  assert.match(pathPolicyServiceSource, /pub fn should_skip_security_scan\(path: &str\) -> Result<bool, String>/)
  assert.match(pathPolicyServiceSource, /is_excluded_path\(path\)\?/)
  assert.match(pathPolicyServiceSource, /is_allowed_path\(path\)/)
  assert.match(pathPolicyServiceSource, /pub fn load_allowlist_entries\(\) -> Result<Vec<AllowlistEntry>, String>/)
  assert.match(pathPolicyServiceSource, /pub fn load_exclusion_entries\(\) -> Result<Vec<ExclusionEntry>, String>/)
  assert.match(scannerCommandSource, /should_skip_security_scan\(&file_path\)\?/)
  assert.match(scannerCommandSource, /skipped_scan_result\(&file_path\)/)
  assert.match(scannerCommandSource, /should_skip_security_scan\(file_path\)\?/)
  assert.match(processScannerServiceSource, /should_skip_security_scan\(target_path\)/)
  assert.match(fileMonitorServiceSource, /should_skip_security_scan\(&file_path\)/)
  assert.match(processMonitorServiceSource, /should_skip_security_scan\(&image_path\)/)
  assert.match(snapshotServiceSource, /should_skip_security_scan\(&proc_info\.path\)/)
})

test('Process and startup scans use cached engine results for process modules', () => {
  assert.match(processScannerServiceSource, /enumerate_process_modules\(pid\)/)
  assert.match(processScannerServiceSource, /scan_or_get_cached\(engine, target_path\)/)
  assert.match(processScannerServiceSource, /"targetType": target_type/)
  assert.match(processScannerServiceSource, /"source": "process_scanner"/)
  assert.match(processScannerServiceSource, /should_skip_security_scan\(target_path\)/)

  assert.match(snapshotServiceSource, /enumerate_process_modules\(proc_info\.pid\)/)
  assert.match(snapshotServiceSource, /scan_or_get_cached\(engine, target_path\)/)
  assert.match(snapshotServiceSource, /"source": "startup_snapshot"/)
  assert.match(snapshotServiceSource, /"targetType": target_type/)
  assert.match(snapshotServiceSource, /scanned_modules/)
  assert.match(snapshotServiceSource, /malicious_modules/)
  assert.match(snapshotServiceSource, /cache_hits/)

  assert.match(scanResultCacheServiceSource, /SCAN_RESULT_CACHE_FILE: &str = "scan_results\.json"/)
  assert.match(scanResultCacheServiceSource, /load_runtime_list::<PersistedScanCacheEntry>/)
  assert.match(scanResultCacheServiceSource, /save_runtime_list\(SCAN_RESULT_CACHE_FILE, &entries\)/)
  assert.match(scanResultCacheServiceSource, /sha256_hex_of_file\(file_path\)/)
  assert.match(scanResultCacheServiceSource, /raw_result/)
})

test('Dev watchers ignore runtime quarantine and database files', () => {
  assert.match(viteConfigSource, /\*\*\/data\/\*\*/)
  assert.match(viteConfigSource, /\*\*\/logs\/\*\*/)
  assert.match(viteConfigSource, /\*\*\/config\/quarantine_index\.json/)
  assert.match(viteConfigSource, /\*\*\/config\/scan_cache\.json/)
  assert.match(tauriIgnoreSource, /data\/\*\*/)
  assert.match(tauriIgnoreSource, /logs\/\*\*/)
  assert.match(tauriIgnoreSource, /config\/quarantine_index\.json/)
  assert.match(tauriIgnoreSource, /src-tauri\/data\/\*\*/)
  assert.match(srcTauriIgnoreSource, /data\/\*\*/)
  assert.match(srcTauriIgnoreSource, /logs\/\*\*/)
  assert.match(srcTauriIgnoreSource, /target\/\*\*/)
  assert.match(gitignoreSource, /src-tauri\/data\//)
})

test('Behavior SQLite database uses app data instead of repository runtime paths', () => {
  assert.match(tauriMainSource, /fn resolve_behavior_database_path\(config: &AppConfig\) -> Result<PathBuf, String>/)
  assert.match(tauriMainSource, /std::env::var\("APPDATA"\)/)
  assert.match(tauriMainSource, /PathBuf::from\(app_data\)[\s\S]*?\.join\("AnXinSecurity"\)[\s\S]*?\.join\(&configured_dir\)/)
  assert.match(tauriMainSource, /fn migrate_legacy_behavior_database/)
  assert.match(tauriMainSource, /std::fs::copy\(&legacy_path, target_path\)/)
  assert.match(tauriMainSource, /let db_root = resolve_behavior_database_path\(&config\)\?/)
  assert.doesNotMatch(tauriMainSource, /let mut db_root = std::env::current_dir/)
})

test('File hook pipe service starts during app setup', () => {
  assert.match(tauriMainSource, /let hook_service = HookService::new\(\)/)
  assert.match(tauriMainSource, /\.start\("anxin_security_filehook", app\.handle\(\)\.clone\(\)\)/)
  assert.match(tauriMainSource, /Failed to start file hook pipe service/)
  assert.match(tauriMainSource, /app\.manage\(Arc::new\(hook_service\)\)/)
})

test('Quarantine table keeps status and action controls readable', () => {
  assert.match(quarantinePageSource, /className="threat-list quarantine-list card"/)
  assert.match(quarantinePageSource, /className="quarantine-status-cell"/)
  assert.match(quarantinePageSource, /className="quarantine-actions"/)
  assert.match(globalCssSource, /\.quarantine-list table/)
  assert.match(globalCssSource, /min-width: 1120px/)
  assert.match(globalCssSource, /\.quarantine-status-cell \.severity-badge/)
  assert.match(globalCssSource, /white-space: nowrap/)
  assert.match(globalCssSource, /\.quarantine-actions \.btn-sm/)
})

test('Quarantine confirmation dialog uses modal surface background', () => {
  assert.match(quarantinePageSource, /className="modal-overlay"/)
  assert.match(quarantinePageSource, /className="modal-surface quarantine-confirm-modal"/)
  assert.doesNotMatch(quarantinePageSource, /className="modal-content"/)
  assert.match(globalCssSource, /\.modal-surface/)
  assert.match(globalCssSource, /background: var\(--acrylic-dark\)/)
  assert.match(globalCssSource, /html\[data-theme="light"\] \.modal-surface/)
  assert.match(globalCssSource, /\.quarantine-confirm-modal/)
})
